Develop
eclipse-volttron/volttron-log-statistics pull request #2
Opened 2024-01-05 21:11 UTC by riley206

Ported log statistics agent to modular.

2024-03-05 23:02 UTC, davidraker requested changes
The port of the agent appears to be largely correct. The agent runs and tests pass. There are serious issues with this agent, however, which predate the port and should be corrected.

2024-03-05 23:02 UTC, davidraker commented on README.md
> +Create a directory called `config` and use the change directory command to enter it.
We're going a bit down in the weeds here. We don't need to explain to people how or where to make a configuration file. We just need to tell them what can be in it.  I would link to the sample config file, and explain the options which can appear in it. This one is short, so it can probably be quoted too, if that seems helpful.

2024-03-05 23:02 UTC, davidraker commented on README.md
> +The Log Statistics agent has 4 required configuration values:
Does it also have optional configuration parameters (I would use the word "parameters", not "values", btw)? If not, I would say that it has four configuration parameters, all of which are required. This keeps them from wondering what the other options might be. If there are, in fact, other options, they should be detailed as well.

2024-03-05 23:02 UTC, davidraker commented on README.md
> +vctl install volttron-log-statistics --agent-config log_stat_config.json --vip-identity platform.log_statistics --start --force
I'm not really sure if we should really be showing using the --force option in these "how to install and start" instructions. As a rule, that should be used when necessary, not as a matter of course.

2024-03-05 23:02 UTC, davidraker commented on README.md
> +
These README files should contain shields indicating whehter their tests are passing and version on PyPi. Some of the agents have more shields, but those should at least be there. 

`![Passing?](https://github.com/eclipse-volttron/volttron-log-statistics/actions/workflows/run-tests.yml/badge.svg)
[![pypi version](https://img.shields.io/pypi/v/volttron-log-statistics.svg)](https://pypi.org/project/volttron-log-statistics/)
`

2024-03-05 23:02 UTC, davidraker commented on README.md
> +- `analysis_interval_secs`:  The interval in seconds between publishing the size delta statistic to the message bus
"between publishes of"

2024-03-05 23:02 UTC, davidraker commented on README.md
> +The Log Statistics agent periodically reads the "volttron.log" file based on the configured interval, computes the size delta from the previous hour and publishes the difference in bytes with a times
There is actually nothing specific to the volttron.log file that I see in this agent. Unless I have missed somthing? That may be why it was written, but really, this is just an agent to monitor changes in the size of any file. I would say "a log file" rather than "the volttron.log file".

2024-03-05 23:02 UTC, davidraker commented on README.md
> +- `file_path`:  This should be the path to the "volttron.log" file
The path of the file to be monitored.

2024-03-05 23:02 UTC, davidraker commented on README.md
> +- `publish_topic`:  Can be used to specify a topic to publish log statistics to which does not get captured by the
So, the "publish topic" vs "historian topic" in this agent isn't really about whether it gets captured by the historian or not. The historian topic is only published every 24 intervals.  Whoever wrote this clearly assumed one hour intervals. (More on this where that code is.) The publish topic is just what gets published on every iteration. So it contains the delta only, whereas the historian topic contains a delta and the standard deviation of 24 deltas.  If we are really going to preserve two topics like this, they should be better explained.

2024-03-05 23:02 UTC, davidraker commented on src/log_statistics/agent.py
> +            if len(self.size_delta_list) == 24:
This only works for the stated purpose if the analysis_interval_sec is 3600.  The default 60 will publish the standard deviation every 24 minutes. This is contrary to the agent's documented behavior.

2024-03-05 23:02 UTC, davidraker commented on src/log_statistics/agent.py
> +                self.vip.pubsub.publish(peer="pubsub", topic=self.historian_topic, headers=headers,
Are we really publishing a single instance delta with a standard devation? This isn't a proper aggregate. Why not the mean delta and standard deviation?

2024-03-05 23:02 UTC, davidraker commented on src/log_statistics/agent.py
> +        self.analysis_interval_sec = config["analysis_interval_sec"]
No agent should ever depend on a configuration file being passed at install time. Especially insofar as this agent does not use the config store, it should have default parameters which can be used if there is not a configuration passed.

2024-03-05 23:02 UTC, davidraker commented on src/log_statistics/agent.py
> +        self.analysis_interval_sec = config["analysis_interval_sec"]
It would probably be better if it used the config store _and_ had default values.

2024-03-05 23:02 UTC, davidraker commented on src/log_statistics/agent.py
> +        self.publish_topic = config["publish_topic"]
The publish parameters are poorly enough named that I would consider doing something like this:
`self.historian_topic = config.get('aggregate_publish_topic', config.get('historian_topic', 'analysis/log_statistics'))
self.publish_topic = config.get('delta_publish_topic', config.get('publish_topic', 'analysis/log_statistics'))`

Then I would document the names as "aggregate_publish_topic" and "delta_publish_topic" (the old names remain supported if the new ones are not provided). This is just my $0.02, though.  I just think it would make the agent more easily understandable.

2024-03-05 23:02 UTC, davidraker commented on src/log_statistics/agent.py
> +                historian_message[1]['log_std_dev'] = {'units': 'bytes', 'tz': 'UTC', 'type': 'float'}
The units would really be more meaningful as rates, i.e. bytes/unit_time.  The published unit _is_, in fact, bytes, but it probably shouldn't be.

2024-03-05 23:02 UTC, davidraker commented on README.md
> +- `file_path`:  This should be the path to the "volttron.log" file
An interesting dilemma is that in modular volttron it that the log file is placed in VOLTTRON_HOME by default. The path will need to be absolute, and this may not be obvious to the user. What if, by default, we used the path where we know volttron.log will be, by default, and made this parameter optional?

2024-03-07 17:12 UTC, riley206 commented on README.md
> +Create a directory called `config` and use the change directory command to enter it.
Well see now I am going against everything else I have already done and what others have said. While I do not disagree with you, I think we should have a discussion about what modular readmes contain. Most of the ones I have seen include creating

2024-03-07 17:15 UTC, riley206 commented on README.md
> +Create a directory called `config` and use the change directory command to enter it.
Oops sorry I though this was sysmon. I will link to the config file but my stance on the creation of this file remains the same.

2024-03-27 19:49 UTC, riley206 commented on src/log_statistics/agent.py
> +        self.publish_topic = config["publish_topic"]
I added config store functionality.

2024-03-27 19:52 UTC, riley206 commented on src/log_statistics/agent.py
> +                historian_message[1]['log_std_dev'] = {'units': 'bytes', 'tz': 'UTC', 'type': 'float'}
I think some extra explanation as to why it should not be bytes would help me.

2024-03-27 21:00 UTC, craig8 approved these changes

2024-03-29 14:51 UTC, davidraker commented on src/log_statistics/agent.py
> +                historian_message[1]['log_std_dev'] = {'units': 'bytes', 'tz': 'UTC', 'type': 'float'}
Normalization: a time-rate is more meaningful in the context of how a file is growing. "Bytes" is only meaningful if you know the interval. If a file grows by 2 GB in an hour, this is a problem. If it grows by 2GB in a year, it probably is not. If you normalize the value as a rate, though, so that it is, say MB/day (configurable?), these examples would become 48,000 MB/day vs 5.5 MB/day. _Now_ you can see the difference.

2024-03-29 20:36 UTC, davidraker commented on src/log_statistics/agent.py
> +    def __init__(self, config_path=None, **kwargs):
You still have a config_path input to the agent, and a function which launches the agent after already loading the config_path. These wouldn't actually be compatible, but you aren't actually even using either one. This should be cleaned up a little. I think best practice for this is to allow the agent to receive a static configuration as before, and to use it to modify the defaults for the config store. I would do the following to clean this up:
* get rid of the separate log_statistics function and put its contents in init. You don't need to, but it isn't really necessary anymore. If you eliminate it, just pass the agent class to vip_main instead of log_statistics. (vip_main provides a config_path, so this matches your agent's __init__ signature already).
* in init, do something like this:
```
    default_config = {...stuff as it is now...}
    if config_path:
        default_config.update(utils.load_config(config_path))
    self.vip.config.set_default('config', default_config)
```
Now you are using anything they pass with --agent-config, you are handling defaults if they have not done so, and the config store is available and takes precedence.

2024-05-01 22:26 UTC, riley206 commented on src/log_statistics/agent.py
> +    def __init__(self, config_path=None, **kwargs):
This was fixed long ago. forgot to close it.

2024-07-31 16:44 UTC, schandrika commented
Add docs folder with index.rst

2024-07-31 16:46 UTC, schandrika commented
In test module change agent_dir path

2024-07-31 20:57 UTC, merged